export const ToDoActionTypes = {
	SET_TASK_LIST: 'SET_TASK_LIST',
	UPDATE_SINGLE_TASK: 'UPDATE_SINGLE_TASK',
	TODO_API_PENDING: 'TODO_API_PENDING',
	TODO_FETCH_LIST: 'TODO_FETCH_LIST',
	TODO_API_ERROR: 'TODO_API_ERROR',
};
