export const UserActionTypes = {
	SET_CURRENT_USER: 'SET_CURRENT_USER',
	REMOVE_CURRENT_USER: 'REMOVE_CURRENT_USER',
	USER_SIGNUP: 'USER_SIGNUP',
	USER_SIGNIN: 'USER_SIGNIN',
	ERROR_IN_API: 'ERROR_IN_API',
	USER_API_ACTION_PENDING: 'USER_API_ACTION_PENDING',
};
