export const UserActionTypes = {
	SET_CURRENT_USER: 'SET_CURRENT_USER',
	REMOVE_CURRENT_USER: 'REMOVE_CURRENT_USER',
	FETCH_DATA_PENDING: 'FETCH_DATA_PENDING',
	FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
	FETCH_DATA_ERROR: 'FETCH_DATA_ERROR',
};
